// <auto-generated />
namespace MvcOnlineTicariOtomasyon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class mig_kargotest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_kargotest));
        
        string IMigrationMetadata.Id
        {
            get { return "202411091244465_mig_kargotest"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
